### ISSUE TITLE
Improve numerical operation usage with optional types

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#893] opened 2021-07-06 17:53 UTC
Consider the following use case, where I want to access a decimal field and perform a numerical operation.  

```ballerina
type Data record {
    record {
        decimal avg?;
    } x?;
};


function getAvg(Data data) returns decimal? {
    decimal? avg = data?.x?.avg;
    if avg == () {
        return ();
    } else {
        return avg / 100d;
    }
}
```

We can't use the Elvis operator in this case. i.e. `(data?.x?.avg ?: 0 )/100`, because it generates an incorrect result. Sometimes back, we did support the following syntax. (which was inspired by JS)

```ballerina
function getAvg(Data data) returns decimal? {
    return data?.x?.avg / 100;
}
```

The above syntax reduces the code complexity compared to current design, So maybe we can rethink introduce the previous semantics back.

**Comment by jclark** [comment] 2021-07-06 23:49
I believe this is a duplicate of #191.

**Closed** 2021-07-07 01:38 UTC
Labels: lang
