### ISSUE TITLE
Intersection of readonly and record type with defaults

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#544] opened 2020-06-11 14:45 UTC
**Description:**
Consider the following example.

```ballerina
type Details record {
    string name;
};

Details det = {name: "Maryam"};

type Employee record {
    Details details = det;
};

public function main() {
    Employee & readonly emp = {};
}
```

Since a value is not specified for the `details` field when creating the `Employee & readonly` value `emp`, the default value `det` would be used. But this default value is not immutable.

Should this 
1. be disallowed at compile-time or
2. result in a panic at runtime, when creating the value or
3. can we use a read-only clone of the default value when creating `emp`?

**Comment by jclark** [comment] 2020-06-12 01:38
A record type descriptor with defaults has similar issues to object classes: it not only denotes a type but also provides a constructor for values of the type.

The problem here is not just with `readonly`. Consider

```ballerina
type A record {
   int x = 1000;
};
type B record {
  byte x;
};
type AB A & B;
AB ab = {};
```

We need some restrictions on applying the intersection operator to record type descriptors with defaults.

**Comment by jclark** [comment] 2020-06-12 05:13
I suggest the following rule: in a type descriptor `T & R` or `R & T`, where R is record type-descriptor, it is an error for R to have a field f of type F with a default unless

- F is a subtype of the type that T requires for f, and
- T does not have a default for f.

@MaryamZi Does that deal with all the problematic cases?

**Comment by MaryamZi** [comment] 2020-06-12 10:26
Yes, I think this should be OK. 

Also, just to confirm, this would apply the same way for just constructor-expressions as default values too, right?

For example, if I have

```ballerina
type Details record {|
    int id = 1000;
|};

type Employee record {|
    Details details = {};
|};
```

The default value for the `details` field is still of type `Details`, so `Employee & readonly` is invalid?

But instead if `Employee` was

```ballerina
type Employee record {|
    Details details = <readonly> {};
|};
```

`Employee & readonly` would be valid?

**Comment by MaryamZi** [comment] 2020-07-08 18:02
Follow up question; the proposed solution would apply to all intersection type descriptors right, not just when it is the contextually expected type for a constructor expression?

I'm wondering if it would be too restrictive where the default is not used directly or is not used at all.

**Case I - Using `.cloneReadOnly()`**

If we were to disallow `T & readonly` where `T` has mutable default values, I would not be able to call `.cloneReadOnly()` on a value of type `T`, even though the immutable clone operation will never fail.

For example, where `Foo` is

```ballerina
type Foo record {|
    map<anydata> m = { // or a variable reference for a mutable value
        initial: false
    };
|};
```

I would not be able to do

```ballerina
Foo f = {};
Foo & readonly fr = f.cloneReadOnly();
``` 

since `Foo & readonly` would not be allowed.


**Case II - Providing an initial value for a field with a default value**

Where `Foo & readonly` is the contextually expected type, when an initial value is provided for `m` in the mapping constructor expression, we validate that the provided value is immutable, or we construct the value with its read-only bit on. And the default value will not be used.

```ballerina
Foo & readonly fr = {m: {initial: true}};
```

Here again, we can construct a valid value that would belong to `Foo & readonly` if it were allowed.

This could happen even with an intersection of two record types.

Should we maybe consider restricting them only when there's a possibility the default value may be used?

**Comment by jclark** [comment] 2021-02-12 10:03
@rdhananjaya If it's easy to implement, my suggestion for now would be to disallow `&` applied to a record type with defaults, and then figure out later how to loosen the restriction.

**Comment by HindujaB** [comment] 2021-06-23 09:19
As per the spec, 
> The static type of a variable declared as configurable is implicitly readonly. 

Therefore, the type of a configurable variable will always be an intersection of the defined type & `readonly`.

```ballerina
type Details record {|
    int id = 1000;
|};
configurable Details details = ?; 
// The type of 'details' is implicitly Details & readonly
```
What is the expected behavior for configurable variables of record type with default values?

**Comment by jclark** [comment] 2021-06-23 10:43
@HindujaB The spec does not address this at the moment. I was hoping just not support this, but the configurable example means that we really have to. I have also found it a pain too.

There's a possible rule in https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-643069011, but it's not really ideal. Let me think about it some more.

**Comment by jclark** [comment] 2022-03-05 01:24
We want to make this work:

```
type T readonly & record {|
    int[] list = [];
};

T t = {};
```

This requires that t.list is a readonly list.

**Comment by jclark** [comment] 2022-03-09 06:35
@MaryamZi What do you think?

**Comment by MaryamZi** [comment] 2022-03-11 04:42
I assume this would be applicable only when `E` is a constructor expression. And given that the type for the closure would be an immutable type, the closures creating immutable values will be used at any depth of a default value.

```ballerina
type Foo record {
    int [] x = [];
};

type Bar record {
    Foo[2] f = [{}, {}];
};

public function main() {
    // `Bar.f`'s default value closure creating an immutable value 
    // will call `Foo.x`'s default value closure creating immutable values.
    Bar & readonly _ = {}; 
}
```

Thinking out loud, can't we use `value:cloneReadOnly` here, instead? IIUC, to fix https://github.com/ballerina-platform/ballerina-spec/issues/491 we would require some additional information about default values (rather than just access to the default value closures), right? Assuming that we have a way of figuring out if a default value is a "pure" constructor (i.e., only has already immutable members and other constructor expressions as members, and no variable reference expressions, no function calls, etc. that result in mutable values at any level), can't we say for

```ballerina
type Foo record { T x = E; };

Foo & readonly foo = {};
```

when `Foo` is intersected with `readonly`, if `T` includes both readonly and non-readonly shapes, we use the result of calling `value:cloneReadOnly` with the result of evaluating the default value closure of `x`, as the value for `x` in `foo`?

This would first create the mutable value though. But we can avoid creating a bunch of closures that may never be used?

**Comment by jclark** [comment] 2022-03-11 05:09
> I assume this would be applicable only when E is a constructor expression.

I am not following your point here. It would apply whenever you need to create a default, which would include cloneWithType.

> And given that the type for the closure would be an immutable type, the closures creating immutable values will be used at any depth of a default value.

Yes.

> Thinking out loud, can't we use `value:cloneReadOnly` here, instead?

I like this idea: I hadn't thought of doing that.  From a specification point of view, we could say we always call `cloneReadOnly` in the readonly case, since that's a no-op if the value is readonly.  A naive implementation would create a mutable value first and then clone it: but a more sophisticated implementation could optimize that into constructing the immutable value directly.

Then I guess we say that in the readonly case if the type of the default expression is not Cloneable then there is no default.

I need to think about this some more, but it looks like a promising approach.

**Comment by MaryamZi** [comment] 2022-03-11 08:34
> > I assume this would be applicable only when E is a constructor expression.
> 
> I am not following your point here. It would apply whenever you need to create a default, which would include cloneWithType.
> 

Sorry, this was regarding the default value expression. If we have something like a function call (where the function may return a mutable value) as the default value expression, I assumed we wouldn't be able to create a closure to produce an immutable value (unless of course we used `cloneReadOnly` there also).

```ballerina
type Configuration record {|
    int[] limits = getDefaultLimits();
|};

isolated function getDefaultLimits() returns int[] => [];

Configuration & readonly readOnlyConfig = {};
```

Using `cloneReadOnly` would solve this. 

My initial suggestion to check for constructor expressions even with `cloneReadOnly` was considering scenarios where the user may expect the same default value to be used (reference equality) across different record values.

```ballerina
int[] defaultLimits = [];

type Configuration record {
    int[] limits = defaultLimits;
};

Configuration c1 = {};
Configuration c2 = {};

boolean _ = c1.limits === c2.limits;
```

But I realize now that this is never the case with mutable values anyway since we allow only isolated expressions as default values.

**Comment by jclark** [comment] 2022-03-11 08:47
> If we have something like a function call (where the function may return a mutable value) as the default value expression, I assumed we wouldn't be able to create a closure to produce an immutable value

Ah, I see your point.  That's a good argument for using the `cloneReadOnly` approach.

> I realize now that this is never the case with mutable values anyway since we allow only isolated expressions as default values.

Couldn't you get this with a function call to an isolated function that used `lock`? In any case, sharing a mutable default record between different records is not a pattern to be encouraged.

**Comment by MaryamZi** [comment] 2022-03-11 11:17
> > I realize now that this is never the case with mutable values anyway since we allow only isolated expressions as default values.
> 
> Couldn't you get this with a function call to an isolated function that used `lock`? 

Wouldn't the restrictions on transferring a value out of the lock statement ensure that we get a clone of anything mutable that may otherwise be shared?

I guess isolated object values may be shared, but they'd fall into the non-Cloneable category or they'd already be immutable.

**Comment by jclark** [comment] 2022-03-12 00:52
You must be right: the whole point of isolated expressions is to avoid returning shared mutable state.

So I think we have answered the question about how to make intersection and readonly work.  But we still have to answer the question about what the general rule for intersection and defaults is.

**Comment by jclark** [comment] 2022-04-19 02:58
Related issue for calling functions with an intersection type, when there are defaults or named arguments (we don't support function intersection types properly at the moment).

**Comment by jclark** [comment] 2022-07-23 02:22
Need to consider #1088 also.

**Comment by jclark** [comment] 2022-07-26 08:12
Since a default value is specified by a closure, when the type is `A&B`, and both `A` and `B` have a default for some field, we cannot in general test whether the default is the same, but there is a simple rule that will handle most cases, consistently with other parts of the language, which is that this should be allowed if 

- the types of the expression for both defaults is the same,
- this type is a singleton, and
- this type is a subtype of `()|boolean|int|string` (for shapes in this type, there is one value for each shape)

**Comment by jclark** [comment] 2022-07-27 06:44
There is another problem lurking here: how should a mapping constructor determine the inherent type when the contextually expected type is an intersection.

The [spec](https://ballerina.io/spec/lang/master/#section_6.7.2) currently deals with just unions (by eliminating those members of the union that are not applicable).

Related to this is that defaults are part of the type descriptor but not the type, but intersections are currently handled semantically (i.e. an intersection is resolved into a type  not a type descriptor).

We also don't have a way to represent the inherent type `readonly & record { ... }` as a record type descriptor.

**Comment by jclark** [comment] 2022-07-29 13:10
#1143 deals how to handle intersections in constructors and cloneWithType.  This issue is then how record defaults are handled as part of this, specifically step 4 of this [comment](https://github.com/ballerina-platform/ballerina-spec/issues/1143#issuecomment-1199027654) 

We deal with the case of `readonly & R` simply by applying `cloneReadOnly` to the default from `R`.

The remaining problem is how to handle defaults when  turning an intersection of two record type descriptors R1 and R2 (either or both may have defaults) into a single record type descriptor R (possibly with defaults).  We can do this independently for each field with a default. For each such field, the individual field descriptor in R may or may not have a default

There are two subcases:
1. A field has a default in one record type descriptor R1 but not in the other R2 (or vice-versa). In this case, we stipulate that the field in R will have R1's default only if the type of the expression for the default in R1 is a subtype of the type of the field in R2.
2. A field has a default in both R1 and R2.  In this case, we stipulate that the field in R will have a default only for the simple cases described in https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-1195154092

**Comment by jclark** [comment] 2022-08-16 02:23
Looks like much of the use of `allOf` in JSON schema is like our `*T`. Instead of

```
type X record { int x; };
type Y record { string y; };
type XY X & Y;
```

it would be better to generate

```
type XY record {
   *X;
   *Y;
};
```

**Comment by jclark** [comment] 2022-08-16 02:26
We can decide whether to do this or not for Update 3 based on needs from OpenAPI/JSON Schema.

**Comment by indikasampath2000** [comment] 2022-08-19 04:24
Hi @jclark 

Yes, we are using the type inclusion for `allOf`.

OpenAPI - https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/asana/openapi.yaml#L6589
Generated Code - https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/asana/types.bal

**Comment by jclark** [comment] 2022-08-19 04:58
@indikasampath2000 I believe OpenAPI allows uses of allOf that doesn't correspond to type inclusion. Have you found any such uses or can they all be handled by type inclusion?

**Comment by indikasampath2000** [comment] 2022-08-19 05:33
We haven't encountered an issue so far using type inclusion for allOf. All OpenAPI definitions we used to generate connectors have allOf as combining schemas.

**Comment by jclark** [comment] 2022-08-22 02:55
Let's make this issue just about intersection with readonly then and do it for Update 3.  We can leave more general intersections for later.

**Comment by jclark** [comment] 2023-06-20 03:29
We need to say what happens if a record type descriptor has a field with a default that expression that is not a subtype of Cloneable. I think the right thing to do in this case is just to say that the intersection doesn't have a default for this field.

**Comment by sanjiva** [comment] 2023-06-20 09:29
Wouldn't it better for this to be an error? User is writing stuff that cannot be correct so why warn and ignore it?

**Comment by jclark** [comment] 2023-06-20 12:47
Typical situation is that the type is defined (and used) as a mutable type, M. Then it also used as an immutable type (by doing readonly & M), possibly by a different user/module. In that case, everything is perfectly fine unless the user tries to construct a value of the immutable type without specifying a default.

**Closed** 2023-06-21 05:46 UTC
Labels: lang, design/incomplete
