### ISSUE TITLE
Default values in intersection types

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#754] opened 2021-02-12 04:41 UTC
**Description:**
This is just to verify that intersection types should not have default values.
```ballerina
type Detail record { int code = -1; };
type E0 error<Detail>;
type E1 error<Detail>;
type Ei E0 & E1;
```

Ei e = error Ei("msg", code = 0); // error detail field `code` is mandatory here.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment] 2021-02-12 09:43
Duplicate of #544.

**Closed by jclark** 2021-02-12 09:43 UTC
