### ISSUE TITLE
Can we allow self in default-expression of method-defn

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#1055] opened 2022-02-24 11:03 UTC
**Description:**

```
Within a method-defn-body, the fields and methods of the object are not implicitly in-scope; instead the variable self is bound to the object and can be used to access fields and methods of the object. 
```
The spec says that `self` can be used to access fields and methods within `method-defn-body`. Let's say we need to assign a field to a defaultable-param as shown below example. 

```ballerina
public class Foo { 
    int i = 0; 

    public function foo(int x = self.i) { 
        
    }

}
```
Can we allow this?

**Comment by jclark** [comment] 2022-02-25 10:14
This is a duplicate of #95.

This isn't allowed at the moment, but maybe we can allow it in the future.

**Closed by jclark** 2022-02-25 10:14 UTC
