### ISSUE TITLE
Can we get rid of empty mapping constructor of parameter annotation?

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-spec#676] opened 2020-12-14 15:35 UTC
**Description:**
I declare a parameter annotation as follows
```ballerina
public type HttpPayload record {|
    string[] mediaType = [];
|};

public annotation HttpPayload Payload on parameter;
```
When using the annotation, the empty mapping constructor is required even when the annotation record fields are no need to be populated.

```ballerina
resource function post hello(@http:Payload {} json payload) {
}

resource function post world(@http:Payload {mediaType:["application/json"]} json payload) {
}
```
Consideration is that the annotation will be used to differentiate the payload parameter from the rest. So 80% of cases, the user would use this with the empty mapping constructor.

Is it possible to default the annotation value to `{}` when the value is not specified?

**Comment by rdhananjaya** [comment] 2021-01-04 05:21
I think this is a spec deviation in the compiler implementation. Created an issue to track and fix this. https://github.com/ballerina-platform/ballerina-lang/issues/27498

**Comment by jclark** [comment] 2021-01-04 09:54
This is a duplicate of #447, which is already fixed in the spec.

**Closed by jclark** 2021-01-04 09:54 UTC
