### ISSUE TITLE
Display name for a package 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-spec#1007] opened 2021-12-15 11:27 UTC
**Description:**

When we publish a package to Ballerina central, the name we want to display there can be different from the package name. 
(package name short and sweet, but display name something distinguishable maybe longer)

For example in Choreo templates, we want to give a proper name for the template. However, package name for the template can be simpler. 

**Describe your problem(s)**

At Choreo, as package API does not give out a proper display name, as a workaround what we do is, include the template name to the first sentence of `package.md` and extract it from a regex. However, if package API could expose a proper display name, it could have been more straightforward and extensible. 

**Describe your solution(s)**

![image](https://user-images.githubusercontent.com/4967046/146177901-03498fa1-0a85-4a31-9023-db4dbd4d8522.png)

Please include `displayName` tag to `Ballerina.toml`. After compiling, bala would have it and package API can expose it.

**Comment by sameerajayasoma** [comment] 2021-12-15 17:02
I think this is a duplicate of https://github.com/ballerina-platform/ballerina-spec/issues/982

**Closed** 2021-12-15 17:02 UTC

**Comment by abeykoon** [comment] 2021-12-16 06:02
IMO, this is different. 
What we need here is a separate tag for the display name. 

In `Ballerina.toml` we like to have,

name = <package name>
displayName = <a display name, can be different from name and more user friendly (with spaces etc)>
description = <one line description so that in ballerina central user can get a quick idea what the library does>

**Use case at Choreo:**

For Choreo getting started samples, we use ballerina templates. We create a Ballerina project with the template and publish it to the Choreo central. The Choreo central expose details about this project to the Choreo UI via package API. When we display getting started samples at Choreo, we need to have a meaningful name for the sample. That name should be exposed through the package API. To do that, we need to have this `displayName` tag in Ballerina.toml.

**Comment by abeykoon** [comment] 2021-12-16 11:44
This is how Choreo shows display names. Each one of this is a package. 
![image](https://user-images.githubusercontent.com/4967046/146365777-6948fb05-968d-440f-90b3-4cc7c7717536.png)
