### ISSUE TITLE
Need langext spec for @tainted

### ISSUE THREAD

**Issue by whizsid** [ballerina-platform/ballerina-spec#598] opened 2020-09-14 20:38 UTC
When I returning a parameter from a function it gives me an error `functions returning tainted value are required to annotate return signature @tainted`. But I refered the `ballerina-spec` site and I couldn't find anything related to `@tainted` signature.

**Comment by jclark** [comment] 2020-09-15 00:24
`@tainted` is a language extension that uses annotations, and so should have a spec linked in here:

https://github.com/ballerina-platform/ballerina-spec/blob/master/langext/README.md

@sanjiva Could you ask the appropriate person to do this?

**Comment by sameerajayasoma** [comment] 2020-09-22 01:29
That would be @rdhananjaya.

**Comment by jclark** [comment] 2020-11-12 02:17
This is a duplicate of #387.

**Closed by jclark** 2020-11-12 02:17 UTC
Labels: langext
